name: Java CI with Maven

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to JFrog Artifactory
        run: mvn deploy
        env:
          registry: "https://govindarajan.jfrog.io/ui/admin/repositories/local/maven-xray-poc/"
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}
          GITHUB_TOKEN: "${{ secrets.REPOSITORY_TOKEN }}"
